sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
notifications:
  email: false

install:
  - pip install -r requirements.txt
  - python setup.py install

#run test
script: order